dialogs/api-schema

- proto/messaging.proto
- proto/search.proto
- scala/build.sbt
Add method for searching users with paging.
Add method for searching users with full-text search.
> feat(proto) - Add methods for searching users

- proto/users.proto
- scala/build.sbt
re-create pull request with conflicts resolved;
> add user preferred locales to user dto.

- docs/feature-flags.schema.json
Flags:
- `notifications.web.newMessageAudioUrl`
- `notifications.web.newMessageIconUrl`
- `notifications.web.newMessageVibrationPattern`
DP-765
> docs(feature-flags): Added flags for message notifications in the web app.

- docs/feature-flags.schema.json
Add confidential policy flags.
> Add confidential policy flags to feature-flags.schema.json

- docs/feature-flags.schema.json
>  max file size

- docs/feature-flags.schema.json
isGlobalSettingsNotificationEnabled and isPassCodeEnabled flags created
> Create two feature flags for user Profile

- .circleci/config.yml
- scala/.sbtopts
- scala/build.sbt
- scala/builder.sh
Support of 2.11, 2.12 & 2.13 scala builds.
> chore(scala): support scala cross builds

- docs/feature-flags.schema.json
add new `chat.media.interactiveElements.maxGroupDescCharCount`
> refactor: format code, rename interactive media related feature flags

- docs/feature-flags.schema.json
feat: Added new feature flags for compress image settings
> Compress image feature flags

- docs/feature-flags.schema.json
add isSberdiskEnabled feature flag
> feat(sberdisk): DP-5483 add isSberdiskEnabled feature flag

- proto/miscellaneous.proto
- scala/build.sbt
This allows us to get original proto sources for additional manipulation.
> feat(scala): bring proto files within JAR

- proto/authentication.proto
- proto/config_sync.proto
- proto/contacts.proto
- proto/counters.proto
- proto/crypto.proto
- proto/definitions.proto
- proto/device_info.proto
- proto/event_bus.proto
- proto/groups.proto
- proto/integrations.proto
- proto/media_and_files.proto
- proto/messaging.proto
- proto/miscellaneous.proto
- proto/obsolete.proto
- proto/peers.proto
- proto/permissions.proto
- proto/privacy.proto
- proto/profile.proto
- proto/push.proto
- proto/raw_api.proto
- proto/reactions.proto
- proto/registration.proto
- proto/search.proto
- proto/sequence_and_updates.proto
- proto/spaces.proto
- proto/stickers.proto
- proto/threads.proto
- proto/typing_and_online.proto
- proto/users.proto
- proto/web_rtc.proto
Akka grpc ignoring scalapb option
> Add java_package option

- proto/miniappsregistry.proto
> feat(miniapps)

- proto/users.proto
Now user can request the data of another user, if that user exists in his contacts
> feat: load user data by contact claim

- .gitignore
- proto/presence.proto
- proto/sequence_and_updates.proto
* Add UpdateGroupTyping.
* Rename TypingAndOnline to Presence.
* Drop unused notification methods.
* Drop `device_category` fields and mark as reserved.
* Add server current time to UserLastSeen.
* Add ability to get online users id in UpdateGroupOnline.
* Add UpdateUserOnline to weak updates.
> feat(presence): Presence enrichment

- docs/feature-flags.schema.json
https://office.dlg.im/jira/browse/DP-8970
https://office.dlg.im/jira/browse/DP-10023
> feat(typing): feature flags to process/emit typingState, also typing timeout

- proto/authentication.proto
reopen pr due to circle-ci glitch.
DP-10021
Stop-gap solution for OEM client SDK initialization.
Target architecture will have one-off short-lived tokens instead.
This api will be used for prototyping and proof-of-concept implementations only.
> feat(OEM): GetSelfInfo ap

- proto/authentication.proto
Add new AuthTransation initiation that is more suitable for SSO-style sign in.
Assumed authorization flow is similar to EmailAuth with EMAILACTIVATIONTYPE_OAUTH2 but does not require email address upfront, allowing for more seamless process.
> feat(sso): add new transaction type and rpc for sso auth;

- proto/sequence_and_updates.proto
Same as https://dialogs.github.io/api-schema/#dialog.RequestSetOnline
> feat(presence): Add device type and timeout to weak command

- DialogSDK-GRPC.podspec
Remove version for support GRPC Objc
> feat(objc_grpc): Remove GRPC version

- docs/feature-flags.schema.json
> feat: Add metrics feature flag

- proto/push.proto
Support for Avrora push server.
> DP-10436: avrora pushes support

- docs/feature-flags.schema.json
добавил фича флаг для списка уведомлений
> feat(platform): DP-11144 add notification history flag

- proto/sequence_and_updates.proto
chore(weaks): dummy commit to trigger publish
> chore(weaks): dummy commit
